apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turbonomic-turbo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: turbonomic
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/turbonomic/turbo
    repoURL: https://github.com/mjperrins/tz-gitops-turbo-60
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
