apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turbonomic-t8c-operator-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: turbonomic
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/turbonomic/t8c-operator-sa
    repoURL: https://github.com/mjperrins/tz-gitops-turbo-60
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
